zabbix_db_name: zabbix
zabbix_db_user: zabbix
zabbix_db_password: zabbixpass
frontend_db_host: 10.168.0.25       # or just 'localhost' if frontend = db server
zabbix_server_ip: 10.168.0.24    # IP of your Zabbix server
