- name: Install Zabbix frontend and dependencies
  ansible.builtin.yum:
    name:
      - zabbix-web-pgsql
      - zabbix-nginx-conf
      - nginx
      - php-fpm
      - php-pgsql
    state: present
    enablerepo: Zabbix_7_2_RHEL9
    disablerepo: SMDS_EPEL_EPEL9

- name: Deploy Zabbix frontend DB config
  ansible.builtin.template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: '0640'
    owner: root
    group: apache

- name: Deploy fixed nginx Zabbix frontend config
  ansible.builtin.template:
    src: zabbix.conf.j2
    dest: /etc/nginx/conf.d/zabbix.conf
    mode: '0644'
    owner: root
    group: root
  notify: restart nginx

- name: Deploy Zabbix PHP-FPM config with timezone
  ansible.builtin.template:
    src: zabbix-php-fpm.conf.j2
    dest: /etc/php-fpm.d/zabbix.conf
    mode: '0644'
    owner: root
    group: root
  notify: restart php-fpm

- name: Enable and start php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: started
    enabled: true

- name: Enable nginx to start at boot
  ansible.builtin.systemd:
    name: nginx
    enabled: true

- name: Open HTTP port in firewalld (zone: public)
  ansible.posix.firewalld:
    port: 80/tcp
    zone: public
    permanent: true
    state: enabled
    immediate: true

- name: Ensure HTTP service is also enabled (zone: public)
  ansible.posix.firewalld:
    service: http
    zone: public
    permanent: true
    state: enabled
    immediate: true
