- name: Install Zabbix frontend from Zabbix repo only
  ansible.builtin.yum:
    name:
      - zabbix-web-pgsql
      - zabbix-nginx-conf
      - nginx
    state: present
    enablerepo: Zabbix_7_2_RHEL9
    disablerepo: SMDS_EPEL_EPEL9

- name: Ensure Nginx config is valid
  ansible.builtin.command: nginx -t
  changed_when: false
  become: true

- name: Configure PHP timezone
  ansible.builtin.lineinfile:
    path: /etc/php-fpm.d/zabbix.conf
    regexp: '^php_value\[date.timezone\]'
    line: 'php_value[date.timezone] = Europe/Zurich'

- name: Deploy Zabbix frontend DB config
  ansible.builtin.template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: '0640'
    owner: root
    group: apache

- name: Enable and start php-fpm
  ansible.builtin.service:
    name: php-fpm
    enabled: true
    state: restarted

- name: Enable and start nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: restarted

- name: Allow HTTP traffic through firewall
  ansible.builtin.firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Add HTTP service to firewalld if not already
  ansible.builtin.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
