- name: Install Zabbix frontend and dependencies
  ansible.builtin.yum:
    name:
      - zabbix-web-pgsql
      - zabbix-nginx-conf
      - nginx
      - php-fpm
      - php-pgsql
    state: present
    enablerepo: Zabbix_7_2_RHEL9
    disablerepo: SMDS_EPEL_EPEL9

- name: Configure PHP timezone
  ansible.builtin.lineinfile:
    path: /etc/php-fpm.d/zabbix.conf
    regexp: '^php_value\[date.timezone\]'
    line: 'php_value[date.timezone] = Europe/Zurich'

- name: Deploy Zabbix frontend DB config
  ansible.builtin.template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: '0640'
    owner: root
    group: apache

- name: Set nginx to listen on port 80 instead of 8080
  ansible.builtin.replace:
    path: /etc/nginx/conf.d/zabbix.conf
    regexp: '^\\s*#?\\s*listen\\s+8080;'
    replace: '    listen          80;'
  notify: restart nginx

- name: Set nginx server_name to localhost
  ansible.builtin.lineinfile:
    path: /etc/nginx/conf.d/zabbix.conf
    regexp: '^\\s*#?\\s*server_name.*'
    line: '    server_name     localhost;'
  notify: restart nginx

- name: Enable and start php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: started
    enabled: true

- name: Enable nginx to start at boot
  ansible.builtin.systemd:
    name: nginx
    enabled: true

- name: Open HTTP port in firewalld (zone: public)
  ansible.posix.firewalld:
    port: 80/tcp
    zone: public
    permanent: true
    state: enabled
    immediate: true

- name: Ensure HTTP service is also enabled (zone: public)
  ansible.posix.firewalld:
    service: http
    zone: public
    permanent: true
    state: enabled
    immediate: true
