- name: Apply common configuration to all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Set up Zabbix server
  hosts: zabbix_server
  become: yes
  roles:
    - zabbix-server

- name: Set up Zabbix frontend
  hosts: zabbix_frontend
  become: yes
  roles:
    - zabbix-frontend

- name: Set up Zabbix agent
  hosts: zabbix_agent
  become: yes
  roles:
    - zabbix-agent
