- name: Install Zabbix agent
  ansible.builtin.yum:
    name: zabbix-agent
    state: present

- name: Configure Zabbix agent
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable and start Zabbix agent
  ansible.builtin.service:
    name: zabbix-agent
    state: started
    enabled: yes

- name: Open Zabbix agent port
  ansible.builtin.firewalld:
    port: 10050/tcp
    permanent: true
    state: enabled
    immediate: yes
