- name: Install Zabbix agent
  ansible.builtin.yum:
    name: zabbix-agent
    state: present

- name: Configure Zabbix agent
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server='
    line: "Server={{ zabbix_server_ip }}"

- name: Enable and start Zabbix agent
  ansible.builtin.service:
    name: zabbix-agent
    state: started
    enabled: yes

- name: Open Zabbix agent port
  ansible.builtin.firewalld:
    port: 10050/tcp
    permanent: true
    state: enabled
    immediate: yes
