---
- name: Install PostgreSQL server and client
  ansible.builtin.yum:
    name:
      - postgresql-server
      - postgresql
    state: present

- name: Initialize PostgreSQL database
  ansible.builtin.command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Start and enable PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Set PostgreSQL local auth to trust
  become: yes
  ansible.builtin.replace:
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: '^local\s+all\s+all\s+.*$'
    replace: 'local   all             all                                     trust'
  notify: Reload PostgreSQL

- name: Ensure IPv4 connections use md5
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    line: 'host    all             all             127.0.0.1/32            md5'
    insertafter: '^# IPv4 local connections:'

- name: Wait for PostgreSQL to accept connections
  become: yes
  become_user: postgres
  ansible.builtin.shell: |
    until pg_isready -q; do sleep 1; done
    
- name: Check if Zabbix user exists
  become: yes
  become_user: postgres
  register: zabbix_user_check
  ansible.builtin.command: psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ zabbix_db_user }}'"

- name: Debug zabbix_user_check result
  debug:
    var: zabbix_user_check.stdout

- name: Create Zabbix user (if needed)
  become: yes
  become_user: postgres
  ansible.builtin.command: >
    psql -c "CREATE ROLE {{ zabbix_db_user }} WITH LOGIN PASSWORD '{{ zabbix_db_password }}';"
  when: zabbix_user_check.stdout != '1'

- name: Create Zabbix database if not exists
  ansible.builtin.shell: |
    psql -tc "SELECT 1 FROM pg_database WHERE datname='{{ zabbix_db_name }}'" | grep -q 1 || \
    psql -c "CREATE DATABASE {{ zabbix_db_name }} OWNER {{ zabbix_db_user }};"
  become_user: postgres

- name: Install Zabbix server (PostgreSQL)
  ansible.builtin.yum:
    name:
      - zabbix-server-pgsql
      - zabbix-sql-scripts
    state: present

- name: Ensure SQL schema file is world-readable
  become: yes
  ansible.builtin.file:
    path: /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz
    mode: '0644'

- name: Import initial schema as postgres user
  become: yes
  become_user: postgres
  ansible.builtin.shell: |
    gzip -dc /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz | \
    psql {{ zabbix_db_name }}

- name: Enable and start Zabbix server
  ansible.builtin.service:
    name: zabbix-server
    state: started
    enabled: yes

- name: Open Zabbix server port
  ansible.builtin.firewalld:
    port: 10051/tcp
    permanent: true
    state: enabled
    immediate: yes
