---
- name: Install PostgreSQL server and client
  ansible.builtin.yum:
    name:
      - postgresql-server
      - postgresql
    state: present

- name: Initialize PostgreSQL database
  ansible.builtin.command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Start and enable PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Change PostgreSQL local auth from peer to md5
  ansible.builtin.replace:
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: '^local\s+all\s+all\s+peer'
    replace: 'local   all             all                                     md5'
  notify: Reload PostgreSQL

- name: Ensure IPv4 connections use md5
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    line: 'host    all             all             127.0.0.1/32            md5'
    insertafter: '^# IPv4 local connections:'

- name: Create Zabbix DB user if not exists
  ansible.builtin.shell: |
    psql -tc "SELECT 1 FROM pg_roles WHERE rolname='{{ zabbix_db_user }}'" | grep -q 1 || \
    psql -c "CREATE USER {{ zabbix_db_user }} WITH PASSWORD '{{ zabbix_db_password }}';"
  become_user: postgres

- name: Create Zabbix database if not exists
  ansible.builtin.shell: |
    psql -tc "SELECT 1 FROM pg_database WHERE datname='{{ zabbix_db_name }}'" | grep -q 1 || \
    psql -c "CREATE DATABASE {{ zabbix_db_name }} OWNER {{ zabbix_db_user }};"
  become_user: postgres

- name: Install Zabbix server (PostgreSQL)
  ansible.builtin.yum:
    name:
      - zabbix-server-pgsql
      - zabbix-sql-scripts
    state: present

- name: Verify SQL schema file exists
  become: yes
  ansible.builtin.stat:
    path: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz
  register: schema_sql_file

- name: Fail if SQL schema file is missing
  ansible.builtin.fail:
    msg: "The Zabbix SQL schema file was not found or not readable."
  when: not schema_sql_file.stat.exists

- name: Import initial schema as postgres user
  become: yes
  become_user: postgres
  ansible.builtin.shell: |
    gzip -dc /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | \
    psql {{ zabbix_db_name }}
  when: schema_sql_file.stat.exists

- name: Enable and start Zabbix server
  ansible.builtin.service:
    name: zabbix-server
    state: started
    enabled: yes

- name: Open Zabbix server port
  ansible.builtin.firewalld:
    port: 10051/tcp
    permanent: true
    state: enabled
    immediate: yes
