- name: Install PostgreSQL server and client
  ansible.builtin.yum:
    name:
      - postgresql-server
      - postgresql
    state: present

- name: Initialize PostgreSQL database
  ansible.builtin.command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Start and enable PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Create Zabbix DB user if not exists
  ansible.builtin.shell: |
    psql -tc "SELECT 1 FROM pg_roles WHERE rolname='{{ zabbix_db_user }}'" | grep -q 1 || \
    psql -c "CREATE USER {{ zabbix_db_user }} WITH PASSWORD '{{ zabbix_db_password }}';"
  become_user: postgres

- name: Create Zabbix database if not exists
  ansible.builtin.shell: |
    psql -tc "SELECT 1 FROM pg_database WHERE datname='{{ zabbix_db_name }}'" | grep -q 1 || \
    psql -c "CREATE DATABASE {{ zabbix_db_name }} OWNER {{ zabbix_db_user }};"
  become_user: postgres

- name: Install Zabbix server (PostgreSQL)
  ansible.builtin.yum:
    name:
      - zabbix-server-pgsql
      - zabbix-sql-scripts
    state: present

- name: Import initial schema
  become: yes
  ansible.builtin.shell: |
    gzip -dc /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | \
    PGPASSWORD={{ zabbix_db_password }} psql -U {{ zabbix_db_user }} -h {{ zabbix_db_host }} {{ zabbix_db_name }}

- name: Enable and start Zabbix server
  ansible.builtin.service:
    name: zabbix-server
    state: started
    enabled: yes

- name: Open Zabbix server port
  ansible.builtin.firewalld:
    port: 10051/tcp
    permanent: true
    state: enabled
    immediate: yes
