---
- name: Install PostgreSQL server and client
  ansible.builtin.yum:
    name:
      - postgresql-server
      - postgresql
    state: present

- name: Initialize PostgreSQL database
  ansible.builtin.command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
    
- name: Deploy pg_hba.conf with access to Zabbix frontend
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    mode: '0600'
    owner: postgres
    group: postgres
  notify: Reload PostgreSQL

- name: Start and enable PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Wait for PostgreSQL to accept connections
  become: yes
  become_user: postgres
  ansible.builtin.shell: |
    until pg_isready -q; do sleep 1; done
    
- name: Check if Zabbix user exists
  become: yes
  become_user: postgres
  register: zabbix_user_check
  ansible.builtin.command: psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ zabbix_db_user }}'"

- name: Debug zabbix_user_check result
  debug:
    var: zabbix_user_check.stdout

- name: Create Zabbix user (if needed)
  become: yes
  become_user: postgres
  ansible.builtin.command: >
    psql -c "CREATE ROLE {{ zabbix_db_user }} WITH LOGIN PASSWORD '{{ zabbix_db_password }}';"
  when: zabbix_user_check.stdout != '1'

- name: Create Zabbix database if not exists
  ansible.builtin.shell: |
    psql -tc "SELECT 1 FROM pg_database WHERE datname='{{ zabbix_db_name }}'" | grep -q 1 || \
    psql -c "CREATE DATABASE {{ zabbix_db_name }} OWNER {{ zabbix_db_user }};"
  become_user: postgres

- name: Install Zabbix server (PostgreSQL)
  ansible.builtin.yum:
    name:
      - zabbix-server-pgsql
      - zabbix-sql-scripts
    state: present

- name: Ensure SQL schema file is world-readable
  become: yes
  ansible.builtin.file:
    path: /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz
    mode: '0644'

- name: Import initial schema as postgres user
  become: yes
  become_user: postgres
  ansible.builtin.shell: |
    gzip -dc /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz | \
    psql {{ zabbix_db_name }}

- name: Enable and start Zabbix server
  ansible.builtin.service:
    name: zabbix-server
    state: started
    enabled: yes

- name: Open Zabbix server port
  ansible.builtin.firewalld:
    port: 10051/tcp
    permanent: true
    state: enabled
    immediate: yes
    
- name: Open PostgreSQL port for remote access
  ansible.posix.firewalld:
    port: 5432/tcp
    permanent: true
    state: enabled
    immediate: yes

